name: Build

on:
  push:
    tags:
    - 'v*'

jobs:
  build_wheels:
    name: Build wheels on ${{matrix.arch}} for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        arch: [auto]
        include:
          - os: ubuntu-20.04
            arch: aarch64

    env:
      CIBW_SKIP: "?p27-* ?p35-*"
      CIBW_ARCHS_LINUX: ${{matrix.arch}}
      CIBW_BEFORE_BUILD_LINUX: "pip install --upgrade pip && python -m pip install -r requirements.txt"
      CIBW_BEFORE_ALL_LINUX: "curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=stable && cp -r /root/.cargo/bin/* /usr/bin/."
      CIBW_BUILD_VERBOSITY: 3
      BUILD_OUTPUT_PATH: wheelhouse

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: docker/setup-qemu-action@v1
        if: ${{ matrix.arch == 'aarch64' }}
        name: Set up QEMU
      - name: Install requirements
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=stable
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.10.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir "$BUILD_OUTPUT_PATH"

      - uses: actions/upload-artifact@v2
        with:
          path: "./$BUILD_OUTPUT_PATH/*.whl"
